### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by XodianKnight** [Alex-the-666/AlexsMobs#1756]
The game freezes then crashes when going to the second page of the Animal Dictionary and me and my friend have no idea why its doing that.

**Comment by KrakenDezJokes** [comment]
a few of us are having this issue right now, It's due to the game trying to render the Transutation table when using JEI (Just enough items) or locating it anywhere in the game. If the game requires to show you the item it will just up and crash due to trying to render it into the game. You will have to avoid using the animal dictionary for now (And JEI if you have that as well)

**Comment by XodianKnight** [comment]
Will do thank you. ^-^
