### ISSUE TITLE
Animal dictionary crashes game when turning page 1.20

### ISSUE THREAD

**Issue by RedW0lfStoneYT** [Alex-the-666/AlexsMobs#1823]
In 1.20 the animal dictionary seems to crash the game when I turn the page, un sure if this is due to the mod pack (slightly flavored) or the mod it's self

**Comment by vinnyg0621** [comment]
I'm having the exact same problem. I'm using my own modpack. here's my report: https://hastebin.com/share/mehakaqole.yaml

**Comment by PacoDaPea** [comment]
I have the same problem too. Heres mine: 
[crash-2023-10-08_09.26.30-client.txt](https://github.com/AlexModGuy/AlexsMobs/files/12839542/crash-2023-10-08_09.26.30-client.txt)

**Comment by MagmaLair** [comment]
There is an error with the Jellyfishes model. If you are having this issue the game will crash whenever it tries to load the model, meaning if they spawn in your game, the world will keep crashing. I suggest for the time being that you go to the config and turn off the jellyfishes spawns so that this doesn't happen. It does not solve the issue with the book, but it keeps your world playable.

**Comment by daddo999** [comment]
There is a way to keep using the dictionary w/0 crashing?

**Comment by coucoul38** [comment]
Stop using Optifine

**Comment by MagmaLair** [comment]
> Stop using Optifine

Not helpful at all. The rubidium port currently doesn't work with the latest update.

**Comment by AlexModGuy** [comment]
dupe #1900
