### ISSUE TITLE
Issues with mobs:Bald Eagle gets stuck while scouting, Tiger crashes the game if fed while aggroed on you

### ISSUE THREAD

**Issue by Sp00kyTom** [Alex-the-666/AlexsMobs#386]
Bald Eagle gets stuck while scouting:Instead of just preventing you from going farther then 150 blocks, it also causes your bald eagle to get stuck, forcing you to shift if you go too far out. Also, if possible I think there should be a visible border or some indication if you're going too far away, because getting randomly stopped is kind of frustrating and 150 blocks is hard to quantify. 

Tiger crash:I hit a tiger, and then fed it porkchops, and it continued to attack me in spite of the blessing. A few second later, the game crashed.

### Tarantula Hawk Aggro Issues:I've tested it with four mobs. The hawk can aggro fine on spiders and zombies, but it can't aggro on tigers and straddlers for some reason. I also noticed it can't teleport to you, even while set to Follow.

Tested this more and wasn't able to replicate it.

Other then these bugs, great update!

**Comment by Jusey1** [comment]
The crash with the tiger happens in general and by chance. It seems to be an AI pathing crash after killing the player. Also, due to a lack of config settings for the tiger. Cannot turn them off.

[crash-2021-05-04_14.00.25-server.txt](https://github.com/Alex-the-666/AlexsMobs/files/6423104/crash-2021-05-04_14.00.25-server.txt)
