### ISSUE TITLE
Crocodile grab cooldown not working

### ISSUE THREAD

**Issue by NixityNull** [Alex-the-666/AlexsMobs#89]
I literally cannot escape these things. The second they see me, they grab me, and every time i break free they immediately grab me again. 

Also, Komodo dragon attack range is a little bit too big. The thing kept biting me from like 3 blocks away.

**Comment by CINQ-MARS** [comment]
Hey, I'm new to this mod (and mods in general)... What's this "grab cooldown" thing? I literally cannot escape crocodiles, can't fight back and I don't know if it's me but it seems a little overpowered... Is there any way to fight it or escape it after it grab you?

**Comment by Zygus42** [comment]
On a similar note - grabbed by crocodile and it's spinning, and there's no way to hit it at all, like it doesn't have a bounding box.  It does stop spinning occasionally, but still can't hit it.  Love the model, but maybe include a setting in the config to replace the fancy attack with a normal attack, otherwise we have to turn them off.
