### ISSUE TITLE
Mimicube corrupted my world 

### ISSUE THREAD

**Issue by HumanNugget** [Alex-the-666/AlexsMobs#941]
[crash-2022-02-14_22.50.11-client.txt](https://github.com/Alex-the-666/AlexsMobs/files/8063252/crash-2022-02-14_22.50.11-client.txt)

Crash report
Hit it with a modded sword 
I had diamond enchanted armor on me
Also curios

**Comment by BasDerilov** [comment]
Same as my issue [here](https://github.com/Alex-the-666/AlexsMobs/issues/936)

Your world isn't corrupted, only your player data file. Removing the player data file from the playerdata folder inside your world folder will cause you to spawn with an empty inventory. You can either cheat your items back (since it's caused by a bug) or use [NBT explorer](https://github.com/jaquadro/NBTExplorer/releases) to move your inventory data from the old player data file to the newly generated one.

**Comment by AlexModGuy** [comment]
>alexsmobs-1.16.0.jar                              

update your mod
